FROM malice/sophos:base

LABEL maintainer "https://github.com/blacktop"

# Install Go binary
COPY . /go/src/github.com/maliceio/malice-sophos
RUN export PATH=$PATH:/usr/local/go/bin \
  && echo "===> Building sophos avscan Go binary..." \
  && cd /go/src/github.com/maliceio/malice-sophos \
  && export GOPATH=/go \
  && go version \
  && go get \
  && go build -ldflags "-X main.Version=$(cat VERSION) -X main.BuildTime=$(date -u +%Y%m%d)" -o /bin/avscan
  # && echo "===> Clean up unnecessary files..." \
  # && apt-get remove --purge -y $buildDeps \
  # && apt-get clean \
  # && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /go /usr/local/go

WORKDIR /malware

ENTRYPOINT ["/bin/avscan"]
CMD ["--help"]
